# Generated by Django 4.2.11 on 2024-06-05 15:17

from django.db import migrations, models
import posts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True, verbose_name='썸네일 URL'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='', validators=[posts.validators.validate_image_extension], verbose_name='썸네일'),
        ),
    ]
